# Site settings
title: Litui
email: litui@litui.net
description: >
  A place where Aria's thoughts go when she is motivated to write.
baseurl: ""
url: "https://www.litui.net"
twitter_username: litui
github_username:  litui
keep_files: ["robots.txt", "keybase.txt"]
exclude: ["punch", "CNAME"]
timezone: "America/Edmonton"
paginate: 1

# Build settings
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]
remote_theme: Codinfox Lanyon