author: Aria Ehren
accounts:
  - site: LinkedIn
    user: Aria Ehren
    uri: https://ca.linkedin.com/in/ariaehren/
    icon: fa-linkedin
  - site: Twitter
    user: litui
    uri: https://twitter.com/litui
    icon: fa-twitter
  - site: Keybase
    user: aria
    uri: https://keybase.io/aria
    icon: fa-key
  - site: Github
    user: litui
    uri: https://github.com/litui
    icon: fa-github