author: Aria Burrell
accounts:
  - site: Twitter
    user: "@litui"
    uri: https://twitter.com/litui
    icon: fa-twitter
  - site: Facebook
    user: Aria Burrell (litui)
    uri: https://facebook.com/litui
    icon: fa-facebook
  - site: LinkedIn
    user: Aria Burrell
    uri: https://ca.linkedin.com/in/ariaburrell/
    icon: fa-linkedin
  - site: Keybase
    user: aria
    uri: https://keybase.io/aria
    icon: fa-key
